[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]

La petición del ayuntamiento de la ciudad de Bruselas es una aplicación que permita a sus ciudadanos tener un mapa 
donde puedan colocar marcadores en distintos sitios. Actualmente solo permite marcar sitios con un tipo de marcador pero posteriormente se podrán escoger diferentes tipos de marcadores dependiendo del lugar, los lugares posibles serán bares, restaurantes, monumentos, paisajes o miradores. Los ciudadanos podrán crear sus propios mapas personalizados y compartirlos con sus amigos.

=== Requirements Overview

[role="arc42help"]
La aplicación deberá permitir a los usuarios añadir y visualizar en un mapa los diferentes marcadores dependiendo que tipo de lugar 
sea.Estos marcadores pueden tener asociadas tanto comentarios, puntuaciones y valoraciones, como fotos en la ubicación del marcador.

Por otra parte, los distintos usuarios pueden compartir sus mapas(con el conjunto de marcadores que tenga asociado) con sus amigos si así lo desean y ver las fotos, 
comentarios, valoraciones y todos los datos que este amigo ha publicado en los marcadores.

La aplicación contará con un filtro para poder ver el mapa, por ejemplo, por categoría (si solo queremos ver las tiendas, restaurantes o cualquiera de los tipos de marcadores enumerados anteriormente), solo los marcadores de los amigos o de un amigo en concreto. Esta funcionalidad todavia no está disponible pero se implementara en próximas versiones.

=== Quality Goals
[options="header",cols="1,2"]
|===
|Objetivos|Descripcion
| Privacidad | Se utlizará la metodologia SOLID para garantizar la seguridad de los datos del usuario, quien será quien nos de acceso a los datos que considere oportunos a través del uso un POD, que será privado e independiente para cada usuario
| Usabilidad | La aplicación deberá ser intuitiva y sencilla de usar para el cliente
| Eficiencia | Se buscara una buena eficiencia de la aplicación, cosa que mejorará a la experiencia del cliente
|===


=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| Equipo de desarrollo | HappySw | Desarrollar la aplicación según las especificaciones y requisitos del cliente
| Cliente | Ayuntamiento de Bruselas | Se espera que entregue una especificación de los requisitos y que siga el projecto para comprobar que se ajusta a los requisitos especificados
| Cliente Potencial | Ayuntamientos de otras ciudades | No se espera que participe en el proyecto, pero se espera que pueda contratar el servicio para tener la aplicación en el futuro para su ciudad
| Usuario Final | Ciudadanos | Que pueda utilizar la aplicación sin problemas con una esperada facilidad de uso y fluidez
|===
