[[section-introduction-and-goals]]
== Introducción y objetivos

La petición del ayuntamiento de la ciudad de Bruselas es una aplicación que permita a sus ciudadanos tener un mapa donde puedan colocar marcadores en distintos sitios. Actualmente solo permite marcar sitios con diferentes tipos de marcadores dependiendo del lugar, los lugares posibles serán bares, restaurantes, monumentos, paisajes o tiendas. Los ciudadanos podrán crear sus propios mapas personalizados y compartirlos con sus amigos.


=== Descripción general de los requisitos

==== Requisitos de alto nivel
* La aplicación permitirá a los usuarios visualizar un mapa donde estos podrán añadir diferentes marcadores.
* Permitirá añadir diferentes tipos de marcadores dependiendo de si este se trata de un restaurante, un bar, un monumento, un paisaje o una tienda.
* En la creacion de estos marcadores se permitirá añadir comentarios o valoraciones, puntuaciones, fotos de estos lugares.
* La aplicación permitirá agregar amigos.
* Se podrá compartir los distintos marcadores con los amigos del usuario donde estos podrán ver las valoraciones, fotos, etc que este marcador tiene asociadas.
* El sistema permitirá utilizar filtros dentro del mapa ya sea por tipo de marcador o por amigo.

==== Requisitos opcionales
* Permitir crear rutas de marcadores.
* Permitir comparar mapas por categorias o tipos de marcadores.
* Permitir que los distintos establecimientos tengan un POD donde los usuarios se puedan conectar.
* Crear un mapa en conjunto, es decir, tener la posibilidad de que varios usuarios añadan marcadores a un mismo mapa.
* Añadir roles entre los diferentes usuarios, como pueden ser: ciudadano, turista y dueño de negocio.


=== Objetivos de calidad
[options="header",cols="1,2"]
|===
|Objetivos|Descripcion
| Privacidad | Se utlizará los principios SOLID para garantizar la seguridad de los datos del usuario, quien será quien nos de acceso a los datos que considere oportunos a través del uso un POD, que será privado e independiente para cada usuario.
| Usabilidad | La aplicación debe ser fácil de usar y entender para el cliente, con el fin de que puedan aprender a utilizarla rápidamente y sin mayores dificultades. De esta manera, se busca mejorar la experiencia del usuario al utilizar la aplicación y reducir el tiempo que requiere para familiarizarse con ella reduciendo la curva de aprendizaje.
| Eficiencia | Se buscara unos cortos tiempos de respuesta de la aplicación, cosa que mejorará a la experiencia del cliente.
|===


=== Stakeholders / Personas interesadas

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Nombre|Contacto|Expectativas
| Equipo de desarrollo | HappySw | Desarrollar la aplicación según las especificaciones y requisitos del cliente
| Cliente | Ayuntamiento de Bruselas | Se espera que entregue una especificación de los requisitos y que siga el projecto para comprobar que se ajusta a los requisitos especificados. También se espera que pueda añadir sitios, comentarios, valoraciones, etc a la aplicación
| Cliente Potencial | Ayuntamientos de otras ciudades | No se espera que participe en el proyecto, pero se espera que pueda contratar el servicio para tener la aplicación en el futuro para su ciudad
| Usuario Final | Ciudadanos | Que pueda utilizar la aplicación sin problemas con una esperada facilidad de uso y fluidez
|===
