name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: npm --prefix webapp install --force
      - name: Build
        run: npm run build --prefix webapp
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: webapp/build/
